# Generated by Django 5.1.1 on 2025-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polso',
            name='adres',
            field=models.CharField(default='Адрес не указан', max_length=50),
        ),
        migrations.AddField(
            model_name='polso',
            name='kontakt',
            field=models.CharField(default='Телефон не указан', max_length=13),
        ),
    ]
